# Build stage
FROM ubuntu:latest

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    make \
    git \
    dpkg-dev \
    apache2 \
    libapache2-mod-wsgi-py3 \
    python3 \
    python3-pil \
    python3-webpy \
    python3-mysqldb \
    python3-psycopg2 \
    imagemagick \
    wkhtmltopdf \
    python3-reportlab \
    python3-requests \
    python3-boto3 \
    memcached \
    python3-memcache \
    python3-xhtml2pdf \
    python3-lxml

# Expose port 5000
EXPOSE 5000

WORKDIR /app