services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=asm3
      - POSTGRES_USER=asm3
      - POSTGRES_DB=asm
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./db:/var/lib/postgresql/data

  memcached:
    image: memcached
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"

  asm:
    image: asm3
    container_name: asm3
    ports:
      - 5002:80
    volumes:
      - ./asm3.conf.dev:/etc/asm3.conf
